# Taller modelos lineales de clasificación - Regresión logística

Sintonice y enrene un modelo de regresión logística para predecir la variable `Churn Label` del dataset **"telco-customer-churn.csv"**, cuya información puede consultar en [IBM](https://community.ibm.com/community/user/businessanalytics/blogs/steven-macko/2019/07/11/telco-customer-churn-1113).

Elimine variables que son claves primaria y que son constantes. También elimine las siguientes variables: Lat Long, Churn Value, Churn Reason, Churn Score.

## Modelo 1

Debe usar `Pipeline` y `ColumnTransformer` para crear un flujo que integre el procesamiento de los datos y el modelado, de manera que evite la fuga de datos.

El procesamiento de los datos debe incluir las siguientes transformaciones:
- Estandarización de variables numéricas
- Imputación de datos nulos
- Codificación de variables categóricas

Escoja una métrica que priorice la clasificación correcta de los clientes que se retiran. Con esta métrica sintonice `C` y `l1_ratio`.

Reporte:

- los resultados de las métricas de validación, entrenamiento y prueba.
- los valores de los hiperparámetros sintonizados.
- la matriz de confusión.
- el reporte de clasificación.

Analice los resultados obtenidos. ¿El modelo esta correctamente ajustado, o está sobreajustado o subajustado? ¿El modelo está balanceado? ¿Con qué clase tiene mejor desempeño?

## Modelo 2

Reporte los coeficientes de este último modelo. ¿Cuáles son las 5 características más importantes de su modelo?

Vuelva a entrenar y sintonizar el modelo, pero ahora seleccione una métrica que priorice etiquetar correctamente a los clientes que no se han retirado.

Reporte:

- los resultados de las métricas de validación, entrenamiento y prueba.
- los valores de los hiperparámetros sintonizados.
- la matriz de confusión.
- el reporte de clasificación.

Analice los resultados obtenidos. ¿El modelo esta correctamente ajustado, o está sobreajustado o subajustado? ¿El modelo está balanceado? ¿Con qué clase tiene mejor desempeño?

Reporte los coeficientes de este último modelo. ¿Cuáles son las 5 características más importantes de su modelo?

**Advertencia:** El entrenamiento de los modelos puede tardar más de 10 minutos. No se preocupe, este es normal. Para reducir un poco el tiempo de entrenamiento pruebe solo 20 valores de `C` y 5 de `l1_ratio`.

## Modulo 1 Solucion

In [15]:
from pathlib import Path

import pandas as pd

DATA_DIR = Path().resolve().parent / 'data' / 'raw'
file_name = 'Telco_customer_churn.csv'
file_path = DATA_DIR / file_name

df = pd.read_csv(file_path)
df.head()

,CustomerID,Count,Country,State,City,Zip Code,Lat Long,Latitude,Longitude,Gender,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
0,3668-QPYBK,1,United States,California,Los Angeles,90003,"33.964131, -118.272783",33.964131,-118.272783,Male,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
1,9237-HQITU,1,United States,California,Los Angeles,90005,"34.059281, -118.30742",34.059281,-118.307420,Female,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
2,9305-CDSKC,1,United States,California,Los Angeles,90006,"34.048013, -118.293953",34.048013,-118.293953,Female,...,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved
3,7892-POOKP,1,United States,California,Los Angeles,90010,"34.062125, -118.315709",34.062125,-118.315709,Female,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
4,0280-XJGEX,1,United States,California,Los Angeles,90015,"34.039224, -118.266293",34.039224,-118.266293,Male,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,89,5340,Competitor had better devices

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 33 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   CustomerID         7043 non-null   object
 1   Count              7043 non-null   int64
 2   Country            7043 non-null   object
 3   State              7043 non-null   object
 4   City               7043 non-null   object
 5   Zip Code           7043 non-null   int64
 6   Lat Long           7043 non-null   object
 7   Latitude           7043 non-null   float64
 8   Longitude          7043 non-null   float64
 9   Gender             7043 non-null   object
 10  Senior Citizen     7043 non-null   object
 11  Partner            7043 non-null   object
 12  Dependents         7043 non-null   object
 13  Tenure Months      7043 non-null   int64
 14  Phone Service      7043 non-null   object
 15  Multiple Lines     7043 non-null   object
 16  Internet Service   7043 non-null   object
 17  Online Security    7043 non-null   object
 18  Online Backup      7043 non-null   object
 19  Device Protection  7043 non-null   object
 20  Tech Support       7043 non-null   object
 21  Streaming TV       7043 non-null   object
 22  Streaming Movies   7043 non-null   object
 23  Contract           7043 non-null   object
 24  Paperless Billing  7043 non-null   object
 25  Payment Method     7043 non-null   object
 26  Monthly Charges    7043 non-null   float64
 27  Total Charges      7043 non-null   object
 28  Churn Label        7043 non-null   object
 29  Churn Value        7043 non-null   int64
 30  Churn Score        7043 non-null   int64
 31  CLTV               7043 non-null   int64
 32  Churn Reason       1869 non-null   object
dtypes: float64(3), int64(6), object(24)
memory usage: 1.8+ MB

In [17]:
df.describe()

,Count,Zip Code,Latitude,Longitude,Tenure Months,Monthly Charges,Churn Value,Churn Score,CLTV
count,7043.0,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,1.0,93521.964646,36.282441,-119.798880,32.371149,64.761692,0.265370,58.699418,4400.295755
std,0.0,1865.794555,2.455723,2.157889,24.559481,30.090047,0.441561,21.525131,1183.057152
min,1.0,90001.000000,32.555828,-124.301372,0.000000,18.250000,0.000000,5.000000,2003.000000
25%,1.0,92102.000000,34.030915,-121.815412,9.000000,35.500000,0.000000,40.000000,3469.000000
50%,1.0,93552.000000,36.391777,-119.730885,29.000000,70.350000,0.000000,61.000000,4527.000000
75%,1.0,95351.000000,38.224869,-118.043237,55.000000,89.850000,1.000000,75.000000,5380.500000
max,1.0,96161.000000,41.962127,-114.192901,72.000000,118.750000,1.000000,100.000000,6500.000000

In [18]:
df.describe(include='object').T
#Cuando en la columna unique aprece el 1 es porque la columna solo tiene un posible valor y no es útil para el modelo

                  count unique                         top  freq
CustomerID         7043   7043                  3668-QPYBK     1
Country            7043      1               United States  7043
State              7043      1                  California  7043
City               7043   1129                 Los Angeles   305
Lat Long           7043   1652      34.159534, -116.425984     5
Gender             7043      2                        Male  3555
Senior Citizen     7043      2                          No  5901
Partner            7043      2                          No  3641
Dependents         7043      2                          No  5416
Phone Service      7043      2                         Yes  6361
Multiple Lines     7043      3                          No  3390
Internet Service   7043      3                 Fiber optic  3096
Online Security    7043      3                          No  3498
Online Backup      7043      3                          No  3088
Device Protection  7043      3                          No  3095
Tech Support       7043      3                          No  3473
Streaming TV       7043      3                          No  2810
Streaming Movies   7043      3                          No  2785
Contract           7043      3              Month-to-month  3875
Paperless Billing  7043      2                         Yes  4171
Payment Method     7043      4            Electronic check  2365
Total Charges      7043   6531                                11
Churn Label        7043      2                          No  5174
Churn Reason       1869     20  Attitude of support person   192

* Cantidad de valores nulos

In [21]:
df.isnull().sum().sort_values(ascending=False).head()

Churn Reason    5174
CustomerID         0
Count              0
State              0
Country            0
dtype: int64

* Porcentaje de valores nulos

In [23]:
df[['Churn Reason']].isnull().sum()*100/df.shape[0]

Churn Reason    73.463013
dtype: float64

* Filas duplicadas

In [24]:
print('Número de registros duplicados: ', df.duplicated().sum())

Número de registros duplicados:  0

Resultados 

* **CustomerID** es una clave primaria.

* Las variables con valores unicos son: **Country**, **state**, **Count** 

* El 73% de los datos de la variable **churn reason** son valores nulos 

* La información que tiene la variable **Lat Long** es la informacion convinada de las variables **Latitude** y **Longitude**.

Soluciones:

* Convertir **CustomerID** en índice, o eliminar la variable.

* Eliminar las variables **Country**, **State** y **Lat Long**.

Convertir **CustumerID** en llave primaria y eliminar las columnas que no ayudan al modelo al modelo

In [25]:
df = df.set_index('CustomerID')
df = df.drop(columns=['Count', 'Country', 'State', 'Lat Long'])
df.head()

,City,Zip Code,Latitude,Longitude,Gender,Senior Citizen,Partner,Dependents,Tenure Months,Phone Service,...,Contract,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Churn Label,Churn Value,Churn Score,CLTV,Churn Reason
CustomerID,,,,,,,,,,,,,,,,,,,,,
3668-QPYBK,Los Angeles,90003,33.964131,-118.272783,Male,No,No,No,2,Yes,...,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,86,3239,Competitor made better offer
9237-HQITU,Los Angeles,90005,34.059281,-118.307420,Female,No,No,Yes,2,Yes,...,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,67,2701,Moved
9305-CDSKC,Los Angeles,90006,34.048013,-118.293953,Female,No,No,Yes,8,Yes,...,Month-to-month,Yes,Electronic check,99.65,820.5,Yes,1,86,5372,Moved
7892-POOKP,Los Angeles,90010,34.062125,-118.315709,Female,No,Yes,Yes,28,Yes,...,Month-to-month,Yes,Electronic check,104.80,3046.05,Yes,1,84,5003,Moved
0280-XJGEX,Los Angeles,90015,34.039224,-118.266293,Male,No,No,Yes,49,Yes,...,Month-to-month,Yes,Bank transfer (automatic),103.70,5036.3,Yes,1,89,5340,Competitor had better devices

Eliminar filas con datos duplicados

In [26]:
df = df.drop_duplicates()

Elimina la columna con datos nulos

In [27]:
df = df.drop(columns=['Churn Reason'])#Elimina de forma permanente la columna 'Churn Reason' del DataFrame.
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7043 entries, 3668-QPYBK to 3186-AJIEK
Data columns (total 27 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   City               7043 non-null   object
 1   Zip Code           7043 non-null   int64
 2   Latitude           7043 non-null   float64
 3   Longitude          7043 non-null   float64
 4   Gender             7043 non-null   object
 5   Senior Citizen     7043 non-null   object
 6   Partner            7043 non-null   object
 7   Dependents         7043 non-null   object
 8   Tenure Months      7043 non-null   int64
 9   Phone Service      7043 non-null   object
 10  Multiple Lines     7043 non-null   object
 11  Internet Service   7043 non-null   object
 12  Online Security    7043 non-null   object
 13  Online Backup      7043 non-null   object
 14  Device Protection  7043 non-null   object
 15  Tech Support       7043 non-null   object
 16  Streaming TV       7043 non-null   object
 17  Streaming Movies   7043 non-null   object
 18  Contract           7043 non-null   object
 19  Paperless Billing  7043 non-null   object
 20  Payment Method     7043 non-null   object
 21  Monthly Charges    7043 non-null   float64
 22  Total Charges      7043 non-null   object
 23  Churn Label        7043 non-null   object
 24  Churn Value        7043 non-null   int64
 25  Churn Score        7043 non-null   int64
 26  CLTV               7043 non-null   int64
dtypes: float64(3), int64(5), object(19)
memory usage: 1.8+ MB

Elimina las filas que contengan datos nulos

In [28]:
df.dropna().info()

<class 'pandas.core.frame.DataFrame'>
Index: 7043 entries, 3668-QPYBK to 3186-AJIEK
Data columns (total 27 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   City               7043 non-null   object
 1   Zip Code           7043 non-null   int64
 2   Latitude           7043 non-null   float64
 3   Longitude          7043 non-null   float64
 4   Gender             7043 non-null   object
 5   Senior Citizen     7043 non-null   object
 6   Partner            7043 non-null   object
 7   Dependents         7043 non-null   object
 8   Tenure Months      7043 non-null   int64
 9   Phone Service      7043 non-null   object
 10  Multiple Lines     7043 non-null   object
 11  Internet Service   7043 non-null   object
 12  Online Security    7043 non-null   object
 13  Online Backup      7043 non-null   object
 14  Device Protection  7043 non-null   object
 15  Tech Support       7043 non-null   object
 16  Streaming TV       7043 non-null   object
 17  Streaming Movies   7043 non-null   object
 18  Contract           7043 non-null   object
 19  Paperless Billing  7043 non-null   object
 20  Payment Method     7043 non-null   object
 21  Monthly Charges    7043 non-null   float64
 22  Total Charges      7043 non-null   object
 23  Churn Label        7043 non-null   object
 24  Churn Value        7043 non-null   int64
 25  Churn Score        7043 non-null   int64
 26  CLTV               7043 non-null   int64
dtypes: float64(3), int64(5), object(19)
memory usage: 1.8+ MB